# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gee', '0005_remove_geendvi_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='geendvi',
            name='author',
            field=models.ForeignKey(default='anon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
