# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gee', '0008_auto_20161027_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geendvi',
            name='author',
        ),
    ]
